POST http://localhost:3001/api/notes 
content-type: application/json

{
  "content": "nueva nota",
  "important": true,
  "userId": "62c56564a8694cf766c51d72"
}

###

POST http://localhost:3001/api/notes 
content-type: application/json

{
  
}