POST http://localhost:3001/api/notes 
content-type: application/json

{
  "content": "Hola mundo",
  "important": true,
  "userId": "62c7e71a09626dc825595df5"
}

###

POST http://localhost:3001/api/notes 
content-type: application/json

{
  
}