POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzdlNzFhMDk2MjZkYzgyNTU5NWRmNSIsInVzZXJuYW1lIjoiam9yZGljYXBlZG8iLCJpYXQiOjE2NTc1MzE3MzYsImV4cCI6MTY1ODEzNjUzNn0.E0NPOXVmH-Fnn9rbcn3Kl16JL8KCDsxM2fc_Dj9Alik

{
  "content": "test",
  "important": true
}